exclude: ^(.venv|docs)/
repos:
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: poetry run bandit
        language: system
        types: [python]
        exclude: ^docs/|^tests/

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --no-strict-optional --ignore-missing-imports
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: poetry run pydocstyle
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types:
          [python]
          # Adapt max line length based on black formatting
        args:
          - "--max-line-length=88"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.*?\.md'
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-docstring-first
      - id: check-case-conflict

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
        args:
          - "--module"
          - "--config=.tflint.hcl"
